# Generated by Django 5.1.7 on 2025-03-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='currency',
            field=models.CharField(choices=[('RUB', '₽'), ('USD', '$'), ('EUR', '€')], default='RUB', max_length=7, verbose_name='Валюта'),
        ),
    ]
