# Generated by Django 5.1.7 on 2025-03-16 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_balance_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='transaction.balance'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('user', 'currency')},
        ),
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('to_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_from', to='transaction.balance')),
                ('to_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_to', to='transaction.balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
