# Generated by Django 5.1.7 on 2025-03-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('goal_type', models.CharField(choices=[('payoff', 'Погасить долг'), ('save', 'Накопить')], default='saving', max_length=31, verbose_name='Тип накопления')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('currency', models.CharField(choices=[('RUB', '₽'), ('USD', '$'), ('EUR', '€')], max_length=7, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Финансовые цель',
                'verbose_name_plural': 'Финансовые цели',
            },
        ),
    ]
