# Generated by Django 5.1.7 on 2025-03-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_currency_alter_task_goal_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Финансовая цель', 'verbose_name_plural': 'Финансовые цели'},
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
    ]
